### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mutluemir081** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#15]
Traceback (most recent call last):
  File "main1.616.py", line 1427, in <module>
  File "C:\Users\Userr\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Userr\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Userr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_compl
ete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.616.py", line 162, in main
IndexError: list index out of range

**Comment by TG-ToolsFree** [comment]
Thats not a bug, you need to put your api id and hash into credentials.txt in the correct format into that file. Look up credentials_example.txt file to see the right format.
