### ISSUE TITLE
Im not sure whats causing this error

### ISSUE THREAD

**Issue by jrBotSpecialist** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#23]
So i have 6 accounts and only 3 of the session file are in the folder because i was trying to trouble shoot the error but that didnt work so i came here, they are all in the group i am adding too but after the 3 accounts are logged in with the session files it does this ...

[!] Account is not in the targeted group!
[+] Joining to My Group Here
Traceback (most recent call last):
  File "main1.624.py", line 1427, in <module>
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.624.py", line 1168, in main
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\users.py", line 43, in _call
    await r.resolve(self, utils)
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\tl\functions\channels.py", line 1394, in resolve
    self.channel = utils.get_input_channel(await client.get_input_entity(self.channel))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\users.py", line 444, in get_input_entity
    peer = utils.get_peer(peer)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\utils.py", line 994, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "C:\Users\Student\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\utils.py", line 132, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.

**Comment by TG-ToolsFree** [comment]
I have never seen this error. If the account is not in the group then it shouldnt even try to join into it. Delete all accounts from the tool, also all session files and login 1 by 1 and try again. For better support, contact us on Telegram: t.me/SubAdder
