### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Mathbate** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#34]
[-] Unexpected Error...
Traceback (most recent call last):
  File "main1.644.py", line 1281, in main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.ChatWriteForbiddenError: You can't write in this chat (caused by InviteToChannelRequest)

**Comment by kiko19871312** [comment]
You need to add those accounts to that group and enable "Add members" option in that group, make it public as well.
