### ISSUE TITLE
I touched the number.csv and then i deleted all accounts but i still have this error.

### ISSUE THREAD

**Issue by Mathbate** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#35]
[!] Getting Peer Flood Error from telegram. Account needs to rest! Changing account...
Traceback (most recent call last):
  File "main1.645.py", line 1281, in main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main1.645.py", line 1430, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.645.py", line 1334, in main
IndexError: list index out of range

**Comment by TG-ToolsFree** [comment]
Your account got limited by Telegram, let it rest. Meanwhile, login with other accounts.
