### ISSUE TITLE
Error thrown right after running .pyc file

### ISSUE THREAD

**Issue by Sevada797** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#43]
Hi I just tested the program, firstly I was getting error which was associated with python version, which I understood and fixed it by setting up alternative python version 3.12, but even then when I run -  ```python3.12 main.pyc```   I get this error 

```
Traceback (most recent call last):
  File "main1.661.py", line 1431, in <module>
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.661.py", line 166, in main
IndexError: list index out of range
```

Though one moment I was seeing the banner and after pressing 4 or 3 then I was getting the error, I would really appreciate if you could've fix that.

**Comment by TG-ToolsFree** [comment]
Hey, make sure to read all steps on INSTALL.txt and create an API ID and HASH. Paste those into credentials.txt in the correct format as in credentials_example.txt
