### ISSUE TITLE
Error when adding and login

### ISSUE THREAD

**Issue by Mathbate** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#45]
Hey i have this error when i want to add users to my group : 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/filestack/utils.py", line 36, in handle_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://upload.filestackapi.com/multipart/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main1.663.py", line 1431, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.663.py", line 1144, in main
  File "main1.663.py", line 274, in number_backup_login
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/filestack/models/client.py", line 157, in upload
    response_json = upload_method(
                    ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/filestack/uploads/multipart.py", line 114, in multipart_upload
    start_response = multipart_request(config.MULTIPART_START_URL, payload, params, security)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/filestack/uploads/multipart.py", line 46, in multipart_request
    return requests.post(url, json=payload).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/filestack/utils.py", line 38, in handle_request
    raise FilestackHTTPError(response.text) from e
filestack.exceptions.FilestackHTTPError: {"error":"Your app is currently blocked due to reaching a free limit or unpaid invoice. To upgrade your account or pay any outstanding invoices, login to your Filestack account here: https://dev.filestack.com/login/","timestamp":1702553173}

**Comment by TG-ToolsFree** [comment]
Fixed, restart the tool and it will update.
